import React, { useState, useEffect } from "react";
import Header from "@/partials/Header";
import Sidebar from "@/partials/Sidebar";
import api from "@/api";
import Swal from "sweetalert2";
import { useNavigate, useParams } from "react-router-dom";

// Component imports
import Input from "@/components/StoreRequest/Input";
import Select from "@/components/StoreRequest/Select";
import TextArea from "@/components/StoreRequest/TextArea"; 
import ItemTable from "@/components/StoreRequest/ItemTable"; // Assuming this handles the requested_items structure

const StoreRequestForm = ({ isEdit = false }) => {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const navigate = useNavigate();
  const { id } = useParams();
  const [errors, setErrors] = useState({});
  
  // 1. Initial State: Directly mapping to 'store_requests' migration fields
  const [form, setForm] = useState({
    date: new Date().toISOString().split("T")[0],
    // ref_no will be generated by the backend
    objective_for: "",
    priority: 3,

    requested_by: "", // Name of the user creating the request
    requested_user: "", // Optional user ID/system field (nullable)
    requested_department: "",
    requested_from: "", // The store/branch/project they are requesting from
    request_remark: "",

    is_fully_issued: false,
    
    // Approval Fields
    approved_by: "", // User ID of the approver (nullable)
    approved_name: "", // Name of the approver (nullable)
    approved_dept: "", // Department of the approver (nullable)
    status: "pending", // Renamed from approved_status to 'status' as per migration
    approved_remark: "", // (nullable)
    approved_date: "", // (nullable)

    // Item Field (JSON column)
    requested_items: [],

    is_fully_issued: false, // (boolean)
  });

  useEffect(() => {
    if (isEdit && id) {
      fetchRequestData(id);
    }
  }, [isEdit, id]);

  // 2. Data Fetching
  const fetchRequestData = async (requestId) => {
    try {
      const response = await api.get(`/store-requests/${requestId}`);
      const data = response.data.data || response.data;
      
      // Merge state and format dates
      setForm(prevForm => ({
        ...prevForm,
        ...data,
        // Format dates correctly for input[type="date"]
        date: data.date ? new Date(data.date).toISOString().split("T")[0] : prevForm.date,
        approved_date: data.approved_date ? new Date(data.approved_date).toISOString().split("T")[0] : "",
      }));

    } catch (error) {
      console.error("Fetch Error:", error);
      Swal.fire({
        icon: "error",
        title: "Error",
        text: error.response?.data?.message || "Failed to fetch store request data.",
      });
      navigate("/store-request/manager"); // Assuming a general list route
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setErrors((prev) => ({ ...prev, [name]: null }));
    setForm((prev) => ({ ...prev, [name]: value }));
  };

  // 3. Item Update Handler
  const handleItemUpdate = (newItems) => {
    // We only need to store the items array, as no financial totals are in the migration
    setForm((prev) => ({
      ...prev,
      requested_items: newItems,
    }));
  };

  // 4. Submission Logic
  const handleSubmit = async (e) => {
    e.preventDefault();
    setErrors({});

    if (form.requested_items.length === 0) {
      Swal.fire({
        icon: "warning",
        title: "Missing Items",
        text: "Please add at least one item to the store request.",
      });
      return;
    }

    // Required fields based on the migration (non-nullable and non-default)
    const requiredFields = [
        "date", // Has default but better to require
        "objective_for",
        "priority",
        "requested_by",
        "requested_department",
        "requested_from",
    ];
    
    let valid = true;
    const newErrors = {};
    requiredFields.forEach(field => {
        // Note: 'priority' is an integer and should be checked differently if needed
        if (!form[field] || String(form[field]).trim() === "") {
            newErrors[field] = ["This field is required."];
            valid = false;
        }
    });

    if (!valid) {
        setErrors(newErrors);
        Swal.fire({
            icon: "error",
            title: "Validation Error",
            text: "Please fill in all required basic information fields.",
        });
        return;
    }

    try {
      if (isEdit) {
        await api.put(`/store-requests/${id}`, form);
        Swal.fire({
          icon: "success",
          title: "Updated!",
          text: `Store Request ${form.ref_no || id} updated successfully.`,
        });
      } else {
        await api.post("/store-requests", form);
        Swal.fire({
          icon: "success",
          title: "Success!",
          text: "New Store Request submitted successfully.",
        });
      }
      navigate("/store-request/manager"); // Navigate to the main list
    } catch (error) {
      if (error.response?.status === 422) {
        setErrors(error.response.data.errors || {});
        Swal.fire({
            icon: "error",
            title: "Validation Error",
            text: error.response.data.message || "Please check the highlighted fields.",
        });
      } else {
        Swal.fire({
          icon: "error",
          title: "Error",
          text: error.response?.data?.message || "An unexpected error occurred during submission.",
        });
      }
    }
  };

  return (
    <div className="flex h-screen overflow-hidden">
      <Sidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
      <div className="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden bg-gray-100 dark:bg-gray-900">
        <Header sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />

        <main className="grow px-4 sm:px-6 lg:px-8 py-8">
          <div className="max-w-7xl mx-auto bg-white dark:bg-gray-800 rounded-xl p-8 shadow-md">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white">
                {isEdit
                  ? `✏️ Edit Store Request: ${form.ref_no || id}`
                  : "➕ Create New Store Request"}
              </h2>

              <button
                type="button"
                onClick={() => navigate("/store-request/manager")}
                className="px-4 py-2 bg-violet-600 text-white rounded hover:bg-violet-700"
              >
                Back to Store Requests
              </button>
            </div>

            <form onSubmit={handleSubmit}>
              {/* --- 1. Basic Information --- */}
              <h3 className="text-xl font-semibold mb-4 text-gray-800 dark:text-white">
                General Request Details
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8 p-4 border rounded-md dark:border-gray-700">
                
                <Input
                  label="Request Date *"
                  name="date"
                  type="date"
                  value={form.date}
                  onChange={handleChange}
                  error={errors.date}
                />
                <Input
                  label="Requested By (Full Name) *"
                  name="requested_by"
                  value={form.requested_by}
                  onChange={handleChange}
                  error={errors.requested_by}
                />
                <Input
                  label="Requesting Department *"
                  name="requested_department"
                  value={form.requested_department}
                  onChange={handleChange}
                  error={errors.requested_department}
                />

                <Input
                  label="Objective/Reason For Request *"
                  name="objective_for"
                  value={form.objective_for}
                  onChange={handleChange}
                  error={errors.objective_for}
                  className="md:col-span-2"
                />
                
                <Select
                  label="Priority *"
                  name="priority"
                  value={form.priority}
                  onChange={handleChange}
                  options={[
                    { value: 1, label: "1 - Urgent" },
                    { value: 2, label: "2 - High" },
                    { value: 3, label: "3 - Normal" },
                  ]}
                  error={errors.priority}
                />

                <Input
                  label="Requested From (e.g., Store/Project/Budget) *"
                  name="requested_from"
                  value={form.requested_from}
                  onChange={handleChange}
                  error={errors.requested_from}
                />
                
                <Input
                  label="Requested User (Optional System Field)"
                  name="requested_user"
                  value={form.requested_user}
                  onChange={handleChange}
                  error={errors.requested_user}
                />
                {/* is fully issued select true or false */}
                <Select
                  label="Is Fully Issued?"
                  name="is_fully_issued"
                  value={form.is_fully_issued ? "true" : "false"}
                  onChange={(e) =>
                    setForm((prev) => ({
                      ...prev,
                      is_fully_issued: e.target.value === "true",
                    }))
                  }
                  options={[
                    { value: "false", label: "No" },
                    { value: "true", label: "Yes" },
                  ]}
                  error={errors.is_fully_issued}
                />
                 <TextArea
                    label="Request Remark"
                    name="request_remark"
                    value={form.request_remark}
                    onChange={handleChange}
                    error={errors.request_remark}
                    className="md:col-span-4"
                />
              </div>

              {/* --- 2. Requested Items --- */}
              <h3 className="text-xl font-semibold mb-4 text-gray-800 dark:text-white border-t pt-4 dark:border-gray-700">
                📦 Items Requested
              </h3>
              <ItemTable
                items={form.requested_items} // Renamed from store_items
                onUpdate={handleItemUpdate}
                error={errors.requested_items}
              />

              {/* --- 3. Approval Information --- */}
              <h3 className="text-xl font-semibold mt-8 mb-4 text-gray-800 dark:text-white border-t pt-4 dark:border-gray-700">
                ✔️ Approval Details
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8 p-4 border rounded-md dark:border-gray-700">
                
                <Select
                  label="Request Status *"
                  name="status" // Aligned with migration 'status' field
                  value={form.status}
                  onChange={handleChange}
                  options={[
                    { value: "pending", label: "Pending" },
                    { value: "approved", label: "Approved" },
                    { value: "rejected", label: "Rejected" },
                  ]}
                  error={errors.status}
                />
                <Input
                  label="Approved By (User ID)"
                  name="approved_by"
                  value={form.approved_by}
                  onChange={handleChange}
                  error={errors.approved_by}
                />
                <Input
                  label="Approver Full Name"
                  name="approved_name"
                  value={form.approved_name}
                  onChange={handleChange}
                  error={errors.approved_name}
                />
                <Input
                  label="Approver Department"
                  name="approved_dept"
                  value={form.approved_dept}
                  onChange={handleChange}
                  error={errors.approved_dept}
                />
                <Input
                  label="Approval Date"
                  name="approved_date"
                  type="date"
                  value={form.approved_date}
                  onChange={handleChange}
                  error={errors.approved_date}
                  className="md:col-span-1"
                />
                <TextArea
                  name="approved_remark"
                  label="Approval Remark"
                  value={form.approved_remark}
                  onChange={handleChange}
                  rows="3"
                  error={errors.approved_remark}
                  className="md:col-span-3"
                />
              </div>

              {/* --- Submit Button --- */}
              <div className="flex justify-end mt-8">
                <button
                  type="submit"
                  className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-md shadow-lg"
                >
                  {isEdit ? "Update Store Request" : "Submit Store Request"}
                </button>
              </div>
            </form>
          </div>
        </main>
      </div>
    </div>
  );
};

export default StoreRequestForm;